"""
Sapti AI — Horse 2: Rememberer Agent
Retrieves personal memories and hive mind insights via pgvector.
"""

import structlog
from app.agents.state import SaptiState
from app.services.memory_service import MemoryService
from app.models.user import UserIdentity

logger = structlog.get_logger()


async def rememberer_node(state: SaptiState) -> dict:
    """Horse 2 — Retrieve personal memories, hive mind insights, and user identity."""
    logger.info("rememberer_start", user_id=state.user_id)

    memory_service = MemoryService()

    # Fetch user identity
    identity_data = await memory_service.get_user_identity(state.user_id)
    user_identity = None
    if identity_data:
        user_identity = UserIdentity(**identity_data)

    # Use the optimized search query generated by the Perceiver (fallback to raw message)
    search_query = state.search_query or state.user_message

    # Search personal memories
    personal_memories = await memory_service.search_personal_memories(
        user_id=state.user_id,
        query=search_query,
    )

    # If vector search returned too few, supplement with recent memories
    if len(personal_memories) < 2:
        recent = await memory_service.get_recent_memories(state.user_id, limit=3)
        existing_ids = {m.memory.id for m in personal_memories}
        from app.models.memory import MemorySearchResult
        for mem in recent:
            if mem.id not in existing_ids:
                personal_memories.append(
                    MemorySearchResult(memory=mem, similarity_score=0.0)
                )

    # Search hive mind
    hive_mind_memories = await memory_service.search_hive_mind(
        query=search_query,
    )

    logger.info(
        "rememberer_complete",
        personal_count=len(personal_memories),
        hive_count=len(hive_mind_memories),
        has_identity=user_identity is not None,
    )

    return {
        "user_identity": user_identity,
        "personal_memories": personal_memories,
        "hive_mind_memories": hive_mind_memories,
    }
